In [12]:
import numpy as np
import matplotlib.pyplot as plt

xs = [10, 100, 25, 67, 74]
ys = [125, 26, 66, 1, 10]

xys = [[10,125], [100,26], [25,66], [67,1], [74,10]]
xys = np.array(xys)

xys

array([[ 10, 125],
       [100,  26],
       [ 25,  66],
       [ 67,   1],
       [ 74,  10]])

In [13]:
x_min = np.min(xys[:,0])
x_max = np.max(xys[:,0])
print(x_min,x_max)

normed_x = (xys[:,0] - x_min) / (x_max - x_min)
print(normed_x)

print('\n')

y_min = np.min(xys[:,1])
y_max = np.max(xys[:,1])
print(y_min,y_max)

normed_y = (xys[:,1] - y_min) / (y_max - y_min)
print(normed_y)

10 100
[0.         1.         0.16666667 0.63333333 0.71111111]


1 125
[1.         0.2016129  0.52419355 0.         0.07258065]


In [14]:
# Multidimensional

min = np.min(xys, 0)
max = np.max(xys, 0)
print(min,max)

print('\n')

normed = (xys - min) / (max - min)
print(normed)
print('\n')
print('\n')
print(xys)

[10  1] [100 125]


[[0.         1.        ]
 [1.         0.2016129 ]
 [0.16666667 0.52419355]
 [0.63333333 0.        ]
 [0.71111111 0.07258065]]




[[ 10 125]
 [100  26]
 [ 25  66]
 [ 67   1]
 [ 74  10]]
